name: threepenny-reloading-example
version: '0.1.0.0'
category: Development
author: Alexey Lebedeff
maintainer: binarin@binarin.ru
license: MIT
homepage: https://github.com/binarin/threepenny-reloading-example
dependencies:
- base >=4.10 && <4.11
- threepenny-gui
- process
- exceptions
default-extensions:
  - ScopedTypeVariables
executables:
  threepenny-reloading-example:
    main: Main.hs
